[package]
name = "hf-safetensors"
version = "0.3.3"
edition = "2021"

[lib]
name = "safetensors"
crate-type = ["staticlib"]

[profile.release]
lto = "fat"

[dependencies]
thiserror = "1.0"
safetensors = "0.3.3"
