[package]
name = "safetensors"
version = "0.4.0"
edition = "2021"

[lib]
name = "safetensors"
crate-type = ["cdylib"]

[profile.release]
lto = "fat"

[dependencies]
thiserror = "1.0"
safetensors = "0.4.0"
